apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-service
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - port: 8080
      protocol: "TCP"
      targetPort: 8080
  type: NodePort
